/*
 * This source file was generated by the Gradle 'init' task
 */
package bcc.textDecisionGame;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class App {
    public static void main(String[] args) {
        JFrame frame = new JFrame("Swing Layout Example");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(400, 300);

        // Use BorderLayout
        frame.setLayout(new BorderLayout());

        JLabel text = new JLabel("You are given a new project in CP3.", SwingConstants.CENTER);
        frame.add(text, BorderLayout.CENTER);

        // Create panel for buttons at bottom
        JPanel buttonPanel = new JPanel(new BorderLayout());

        JButton leftButton = new JButton("Start today ");
        JButton rightButton = new JButton("Wait till thte day its due");

        leftButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                text.setText("YOUR SCENARIO HERE");
                leftButton.setText("YOUR NEW OPTION 1 HERE");
                rightButton.setText("YOUR NEW OPTION 2 HERE");
            }
        });

        buttonPanel.add(leftButton, BorderLayout.WEST);
        buttonPanel.add(rightButton, BorderLayout.EAST);

        frame.add(buttonPanel, BorderLayout.SOUTH);

        // Show frame
        frame.setVisible(true);
    }
}
